### ISSUE TITLE
You have an undeclared dependency on attrs

### ISSUE THREAD

**Issue by FollowTheProcess** [obendidi/httpx-cache#21]
**Describe the bug**

Hey there! I was using your project and couldn't figure out why I was getting weird errors that didn't show up in my dev environment.

It seems like you use attrs but don't declare it as a dependency in `pyproject.toml`, my dev environment had it in from some other project hence why I only saw the errors once I installed my project outside the dev environment.

Imported here: https://github.com/obendidi/httpx-cache/blob/7789306f6b04023f2149d9b153c7d0ad134b5372/httpx_cache/utils.py#L8

Used here: https://github.com/obendidi/httpx-cache/blob/7789306f6b04023f2149d9b153c7d0ad134b5372/httpx_cache/utils.py#L94

But it's not listed in dependencies in `pyproject.toml` here: https://github.com/obendidi/httpx-cache/blob/7789306f6b04023f2149d9b153c7d0ad134b5372/pyproject.toml#L30

When I ran my project I got `ModuleNotFoundError` and traced it back here.

**Expected behavior**

The dependency should be declared in `pyproject.toml`

**Screenshots**

I forgot to grab any screenshots but I hope the problem is clear

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] MacOS
 - Version [e.g. 22] Python 3.10.1

**Additional context**

**Comment by obendidi** [comment]
Thanks for the PR, I'll prepare a new release shortly with the fix ^^

**Comment by FollowTheProcess** [comment]
No worries! Happy to help, great project btw, fits my use case perfectly

**Comment by obendidi** [comment]
Glad to hear that, don't hasitate if you have any feature requests ^^.
