### ISSUE TITLE
Hope to use redis cache

### ISSUE THREAD

**Issue by EchoShoot** [obendidi/httpx-cache#47]
Great job, giving httpx the ability to cache. It is very helpful in crawling crawler. At present, with the development of distributed crawler, local file cache is difficult to help distributed crawler speed up. It is recommended to implement redis cache

**Comment by obendidi** [comment]
Hello @EchoShoot 

that's indeed the plan, ideally I would like to use [aiocache](https://github.com/aio-libs/aiocache) directly and all it's supported backends

**Comment by obendidi** [comment]
Latest release `v0.9.0` has basic support for a redis cache :+1:

**Comment by EchoShoot** [comment]
it is awesome!
