### ISSUE TITLE
Patch httpx dependency

### ISSUE THREAD

**Issue by ludaavics** [obendidi/httpx-cache#59]
Could you please update the dependencies to allow httpx version 0.23? it looks like it patches some [critical vulnerability](https://git.drwholdings.com/advisories/GHSA-h8pj-cxx2-jfg2).
thanks!

**Comment by obendidi** [comment]
Hi!
Started a PR #60, but a lot of tests are failing so it will need some work/time :)

**Comment by obendidi** [comment]
A new version `0.6.0` has been released with `httpx@0.23.0`
