### ISSUE TITLE
Conda 

### ISSUE THREAD

**Issue by ludaavics** [obendidi/httpx-cache#73]
Hi,

Would you consider making your library available on conda?
Thanks!

**Comment by ludaavics** [comment]
I can do the initial set up but you would have to agree to be a maintainer and release new versions of your library to conda as well as pypi.

**Comment by ludaavics** [comment]
I've created a [PR](https://github.com/conda-forge/staged-recipes/pull/21364) on conda forge... please comment in there if you're OK being a maintainer.. it should be pretty [low effort](https://github.com/conda-forge/staged-recipes#9-what-does-being-a-conda-forge-feedstock-maintainer-entail)

**Comment by obendidi** [comment]
sure, I have no problem with that

The PR seems to be already merged, do I need to do something to also be a maintainer on conda ?

Thanks for doing the initial setup

**Comment by ludaavics** [comment]
yeah didn't expect them to merge right way. I guess i didn't have your name as a maintainer so they couldn't know anything was pending.
I'm making this up as I go along, but i think all you need to do is submit a PR to the [auto-generate repo](https://github.com/conda-forge/httpx-cache-feedstock/search?q=ludaavics) adding your name along side mine?
