### ISSUE TITLE
`FileCache` on an `AsyncClient` doesn't work with `s3fs`

### ISSUE THREAD

**Issue by mjkanji** [obendidi/httpx-cache#86]
**Is your feature request related to a problem? Please describe.**
I'd like to use the `FileCache` backend to store the cache to object storage (S3), instead of the local disk. Since `s3fs`, which is built on top of `fsspec`, provides an abstract filesystem for S3 and `universal_pathlib`'s `UPath` is a subclass of `pathlib.Path` and provides a similar interface to any `fsspec`-backed file system, I was hoping to simply pass a `UPath` as the `cache_dir` for a `FileCache` and have it work automatically.

While this does work for the synchronous client:

```python
import httpx_cache
from upath import UPath

bucket = UPath("s3://my-bucket")
cache_dir = bucket / "cache_test"
cache = httpx_cache.FileCache(cache_dir=cache_dir)

def main():
    with httpx_cache.Client(cache=cache) as client:
        response1 = client.get("https://httpbin.org/get")
        response2 = client.get("https://httpbin.org/get")
    return response2

main()

# Shows a new file created for the cache
print([f for f in cache_dir.iterdir()])
```

It doesn't work with the AsyncClient:

```python
import asyncio

import httpx_cache
from upath import UPath

bucket = UPath("s3://my_bucket")
cache_dir = bucket / "async_cache"
cache = httpx_cache.FileCache(cache_dir=cache_dir)

async def async_main():
    async with httpx_cache.AsyncClient(cache=cache) as client:
        response1 = await client.get("https://httpbin.org/get")
        response2 = await client.get("https://httpbin.org/get")
    return response2


asyncio.run(async_main())

# No cache files are created
print([f for f in cache_dir.iterdir()])
```

If the `async_cache` prefix doesn't exist in the bucket already, I'm getting a `FileNotFoundError: my_bucket/async_cache`. 

To circumvent this, I created a dummy file to ensure the prefix existed. The script now runs. However, no files are created for the cache.

**Comment by obendidi** [comment]
Hey @mjkanji, 

Thanks for opening the issue, I'll have a more detailed look later when I have the time :)

First question, does `UPath` support async operations ?

It makes sense for it not to work with the async client, since we wrap the `pathlib.Path` object with an `anyio.Path` wrapper to add async I/O ops:

https://github.com/obendidi/httpx-cache/blob/adbbeda5d5a357f88bde00de7c77ed135485aa21/httpx_cache/cache/file.py#L67-L78

It works with the sync client since we use the user provided path directly.

**Comment by obendidi** [comment]
A new version has been released with async support for `UPath`, let me know if it works out to close the issue :)

https://obendidi.github.io/httpx-cache/guide/#fsspecuniversal_pathlib-integration

**Comment by mjkanji** [comment]
> A new version has been released with async support for `UPath`, let me know if it works out to close the issue :)

It is working, indeed! Thank you for the quick fix!

A quick clarification: does this also work for the (Async)CacheControlTransport or just the clients?

**Comment by obendidi** [comment]
should work for everything, the clients use the `CacheControlTransport` inside

**Comment by mjkanji** [comment]
Awesome, thanks!
