### ISSUE TITLE
Cache Confirmation Header

### ISSUE THREAD

**Issue by shivsah** [obendidi/httpx-cache#87]
How about adding an header to the response to confirm if the request is from cache or not.

**Comment by obendidi** [comment]
There is actually a property set on the response that indicates whether the response is from cache or not. It's not actually documented, so I'll add it to the docs, thanks for bringing it up.

Example:

```py
import httpx_cache

with httpx_cache.Client() as client:
  response1 = client.get("https://httpbin.org/get") # will be cached
  response2 = client.get("https://httpbin.org/get") # will get it from cache

assert response1.from_cache is False
assert response2.from_cache is True
```

FWI, the property is set here:

https://github.com/obendidi/httpx-cache/blob/main/httpx_cache/transport.py#L47-L81

**Comment by obendidi** [comment]
Added to docs here: https://obendidi.github.io/httpx-cache/guide/#usage-with-default-values
