### ISSUE TITLE
Comparison to httpx-caching

### ISSUE THREAD

**Issue by Julian** [obendidi/httpx-cache#90]
Hi there! Nice looking library.

**Is your feature request related to a problem? Please describe.**
The README mentions this project is inspired in part by `httpx-caching` -- but doesn't say what differences it has.

**Describe the solution you'd like**
A small comparison or even sentence describing why this exists as distinct from `httpx-caching`.

I know nothing about what came first, nor do I know (yet) what the answer is to how they differ, but regardless thanks for making the library!

**Comment by obendidi** [comment]
Closing because this project will be archived in favor of: https://github.com/karosis88/hishel
